### PR TITLE
- setter for frost protection mode

### PR DESCRIPTION
**Pull request by bretttickx**

### CODE REVIEW

**Comment by bretttickx** [comment]
@andylockran  Hi Andy just added a method to set frost protection on/off, Im trying to get my changes to the home assistant component finally over the line :-) it s failing on the travis build

**Comment by bretttickx** [comment]
Hi @andylockran 
have you had time to take a look at this?

**Comment by andylockran** [comment]
Looks good. Can you increment the version in setup.py and I'll merge.

**Comment by bretttickx** [comment]
This is done nice one Andy ;-)

**Comment by andylockran** [comment]
Tryng to work out why travis is failing          - public repo but complaing about permissions. :(

**Pull request merged**
