### PR TITLE
return temperature based on sensor selection

### PR DESCRIPTION
**Pull request by bretttickx**

### CODE REVIEW

**Comment by bretttickx** [comment]
Hi @andylockran noticed you got the home assistant component updated :-) nice one, i've been working on it as well but not had time to finished it! I've just tested it on my stats and it works but my under floor heating is a water based system and uses an air sensor so I've made a change to return current temperature based on sensor type. I've noticed a few other small issues but theses need to be changed within the home assistant component which i'll take a look at :-)

**Comment by NigelCoxon** [comment]
Thats great @bretttickx 
Just what I needed to fix my issue https://github.com/home-assistant/home-assistant/issues/29986
My system uses the inbuilt & remote air sensors.

Is there a way I can try this change on my system, before it is integrated in a main release?
Cheers
Nigel

**Comment by andylockran** [comment]
Sure - I can help on this too; to set which sensor is used for the reading is fairly straightforward.

I’m away at the moment until next week.

**Comment by StuartJeffery** [comment]
Hi Andy,

Just found that you have made some progress here. 

i seem to make a connection but get CRC Incorrect om the logs? Any pointers?

Stuart

**Comment by dmcginty1979** [comment]
HI All, Experiencing this issue on HA 115.4. Similarly only getting readings from floor stats on prt-n models. @bretttickx you created a custom component in an earlier issue 13146, can you make that available to get around this until this gets committed ?

**Comment by andylockran** [comment]
Does someone else want to take ownership of this repo and the pypi package?

I'm really sorry, but my time is currently fully spent on other projects.

**Comment by bretttickx** [comment]
Hi @andylockran,
Yeah i can take ownership no worries

**Comment by bretttickx** [comment]
@dmcginty1979 ill try get some time this week put the custom component in a repo as a work around

**Comment by bretttickx** [comment]
@dmcginty1979 see how you get on with this:
https://github.com/bretttickx/HA-heatmiser-component

**Comment by andylockran** [comment]
Awesome - i'll transfer ownership later on today I hope :)

**Comment by dmcginty1979** [comment]
Brilliant Bret,

I'll test that out tonight.

Thanks
Donal

________________________________

**Comment by bretttickx** [comment]
@andylockran any movement on this? Be nice to get the hass component put to bed
Cheers
Brett

**Comment by andylockran** [comment]
Do you have a pypi account too?

**Comment by bretttickx** [comment]
nice one @andylockran  i do now ;-) username -  brettyboo

**Pull request merged**
